### ISSUE TITLE
Field listener logic broken

### ISSUE THREAD

**Issue by apixandru** [xwic/jWic#30]
The implementation of de.jwic.base.Field#setValues(String[]) specifies that a new value will be set only if it's different from the old one, however the check for equality is broken, it checks using Arrays.equals(this.values, values);

Because the initial value of the field is null instead of an empty string array, when the new value is an empty string array, null is different from an empty string array so the event is triggered when it shouldn't.

The workaround for this misbehavior is a "if (event.getOldValue().equals(event.getNewValue())) return;" as the first line, but this shouldn't be necessary.

**Comment by lippisch** [comment]
You are right, the question is when to fix this. Applicaitons may have been build based on this specific behavior, which would break now.

My recommendation would be to changes this with the next release version (v5.3.0).
