### ISSUE TITLE
Multi line input box rendering issue

### ISSUE THREAD

**Issue by apixandru** [xwic/jWic#31]
When toggling visibility on a multi line inputbox, the text disappears. 
The value is still there as indicate by getText(), it's just not rendered

sample 

		final InputBox ib = new InputBox(this, "scooby");
		ib.setText("i was prepopulated, you know");
		ib.setMultiLine(true);
		final RadioGroup radioGroup = new RadioGroup(this, "scoobyrd");
		radioGroup.addElement("one");
		radioGroup.addElement("two");
		radioGroup.addElementSelectedListener(new ElementSelectedListener() {

			@Override
			public void elementSelected(final ElementSelectedEvent event) {
				ib.setVisible(false);
				ib.setVisible(true);
				System.out.println(ib.getText());
			}
		});

**Comment by apixandru** [comment]
this appears to be an issue in chrome  43.0.2357.65 m, not so much in firefox developer edition or internet explorer
inspecting the html element, the text is inside the text area, it's just not rendered by chrome

**Comment by apixandru** [comment]
Appears to be related to this issue
https://code.google.com/p/chromium/issues/detail?id=487352

**Comment by lippisch** [comment]
It seems that there are workaround, that could be applied to the InputBox js code to set the text again after updating the element. But it seems to apply only to one Chrome version.... 

Now the question is: Should we apply a "workaround" in the jWic code to handle issues of this particular version... or do we hope on users recognizing that a lot of other pages dont work as well and Google patches Chrome quickly...?

**Comment by apixandru** [comment]
Looks like chrome fixed their bug. No need for a workaround.
