### ISSUE TITLE
Add .show() and .hide() to Control to handle visibility?

### ISSUE THREAD

**Issue by lippisch** [xwic/jWic#32]
This is more of a discussion thread..

Currently, control visibility is toggled using `.setVisible(state)` on the control. But some folks asked for a convenience method instead to show or hide the control.

I think it would make the usage of controls more convenient, but on the other side it creates also more methods making controls more complex overall. You may say: Just because of those two methods? Well, yeah, maybe those two don't matter, but if you think of this as an architectural pattern, we would also need things like `enable()` or `disable()` and so on...

What are your thoughts?

**Comment by karlaboss11** [comment]
> In my personal opinion this is difficult question ;). In swing method show and so on is already obsolete and to control the visibility is used method setVisible. On the other site in javafx there is show/ hide method used to control the visibility… so…..


I think personally as a old swing user .. leave it like it is ;) 

Karolina

**Comment by andreipat** [comment]
I definitely want to have the getter/setters. I don't have a strong opinion on the action methods like "show"/ "hide", they seem easier to use because you don't need a parameter, but you have to remember two extra method names. And these type of methods sometime make me wonder if I should call "isShown" or "isHidden" to know the state. Oh, wait, it was isVisible, so the code gets implemented like this:

if (control.isVisible()) {
    control.hide();
}

vs.

if (control.isVisible()) {
   control.setVisible(false);
}

Might not look like a big deal, but when you review thousands of line of code in one day, things like this add up to make a difference.

**Comment by adrianionescu** [comment]
I was just phrasing my input, but Andrei beat me to it. I also think the setters/getters are a better approach, for the same reason Andrei already mentioned. 

To nitpick for another reason: we might need specific show/hide methods for certain controls to add additional behavior (e.g. calculate the size of a window) and, when overriding, we might forget to actually toggle the visible flag to true. While setters are rarely overridden and they do a single and straightforward thing.

And, final reason, we save our keyboards :)

setVisible(computedFlag) 

vs.

if (computedFlag) {
    show();
} else {
    hide();
}

**Comment by lippisch** [comment]
Ok, so let's mark this down then as a standard architectural pattern for all jWic controls:

We do use getter/setter methods to set and evaluate the state of a property without creating action methods that simply change a property.

So for the `visibility` property for example, we just have:
   `setVisible(boolean)`  and `isVisible()`

and do NOT create action methods like `show()` or `hide()`

This said: A control may still implement action methods if they do not only relate to the state of the property but actually do something more complex. A dialog for example, may still use `show()` and `hide()` methods. But those methods will most likely do a lot of other things than just set the visibility property...
