### ISSUE TITLE
StackedBarChart - Legend doesnt work

### ISSUE THREAD

**Issue by lippisch** [xwic/jWic#44]
The Legend does not work properly on the StackedBarChart.

I'd suggest to add a sample StackedBarChart to the Dashboard Demo, to see the problem.

**Comment by vzhovtyuk** [comment]
Dashboard demo contains StackedBarChart already, but legend was not available. Its enabled now.
Legend colors were also fixed in vitaliy_stackedbarchart_legend.
Spotted also few tooltip issues with other charts. Will be reported separately.

**Comment by vzhovtyuk** [comment]
StackedBarChart still need to be added to Deshboard demo.
