### ISSUE TITLE
Tooltip colors on LineChart and RadarChart

### ISSUE THREAD

**Issue by Ephislash** [xwic/jWic#46]
The colors representing values on tooltips in these 2 controls are not the same as colors used for values. Other chart controls seem fine (for example BarChart).

Scenario: User hovers mouse over a point where the values are red=16 and blue=6. 
Expected: Tooltip shows red 16 and blue 6.
Actual: Both values are shown with the same color (yellow)
![capture](https://cloud.githubusercontent.com/assets/6900633/13114896/d7b81bca-d595-11e5-8c76-4475cb995b33.PNG)

**Comment by vzhovtyuk** [comment]
Fixed in vitaliy_line_and_radar_chart_tooltip_colors. Pls review.
